{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "optipilot.fullname" . }}-controller
  labels:
    {{- include "optipilot.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "optipilot.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "optipilot.serviceAccountName" . }}
    namespace: {{ include "optipilot.namespace" . }}
{{- end }}

