{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "optipilot.serviceAccountName" . }}
  namespace: {{ include "optipilot.namespace" . }}
  labels:
    {{- include "optipilot.labels" . | nindent 4 }}
{{- end }}

